services:
  website:
    env_file:
      - .env
    build:
      context: .
    ports:
      - "${APP_PORT}:8000"
    volumes:
      - ".:/var/www/html"
    networks:
      - red
    depends_on:
      - mysql
  mysql:
    image: "mysql/mysql-server:8.0"
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - database:/var/lib/mysql
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./sql/create-db.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
      - red
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-p${DB_PASSWORD}"
      retries: 3

      timeout: 5s
networks:
  red:
    driver: bridge
volumes:
  database:
    driver: local
